### ISSUE TITLE
关于群晖NAS docker运行报错

### ISSUE THREAD

**Issue by BabyDriver2023** [AoEiuV020/ps4broadcast-docker#1]
![8a123f61d7d80802d50d19d31feff18](https://github.com/AoEiuV020/ps4broadcast-docker/assets/124128728/d7ffe878-ecb5-423c-ad8b-0fe5fbac9b34)

运行报错"WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64)and no specific platform was requested"

麻烦能支持一下X86么，谢谢。

**Comment by AoEiuV020** [comment]
还真忘了这个架构问题，我抽空看看能不能搞定用github actions自动打包上传个x8架构的，

**Comment by AoEiuV020** [comment]
现在有了，使用github actions跑的docker buildx跨架构打包发布，现在支持依赖的镜像node:8.7.0-slim支持的所有架构，包括你需要的linux/amd64，
我现在没有条件测试，还麻烦你自己试试，应该没有问题，
<img width="778" alt="image" src="https://github.com/AoEiuV020/ps4broadcast-docker/assets/11682198/02c324ed-e132-490c-b7c5-a136ef39f1f7">

**Comment by BabyDriver2023** [comment]
> 现在有了，使用github actions跑的docker buildx跨架构打包发布，现在支持依赖的镜像node:8.7.0-slim支持的所有架构，包括你需要的linux/amd64， 我现在没有条件测试，还麻烦你自己试试，应该没有问题， <img alt="image" width="778" src="https://private-user-images.githubusercontent.com/11682198/330857107-02c324ed-e132-490c-b7c5-a136ef39f1f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Mjg4MjMsIm5iZiI6MTcxNTgyODUyMywicGF0aCI6Ii8xMTY4MjE5OC8zMzA4NTcxMDctMDJjMzI0ZWQtZTEzMi00OTBjLWI3YzUtYTEzNmVmMzlmMWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAzMDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZWUxZmRlYTcxNzhiYWFiOWE2NDY3NWZkYTk1YTFhNGI3NzQxZmY1NmZjNzRlZmMyYjVkNzMzNjAxOGZiMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eYdsyfFPaFR1k-48PbiRhmxEcCb18tslvkLWqZuelT0">

已成功跑起来，还在按使用说明调试中。

**Comment by BabyDriver2023** [comment]
![image](https://github.com/AoEiuV020/ps4broadcast-docker/assets/124128728/b9406cd3-ca4b-47b6-a747-0e86d6b580c0)
请教，这一步没太看懂，PS5的自身IP地址、网关地址设置成什么？  谢谢

**Comment by AoEiuV020** [comment]
大家的网关情况都不一样，我这里readme针对的是在使用这项目之前就已经有openwrt+uu配合ps5设置好了的情况，其他情况没法一概而论， 

如果你目前ps5连接的路由不是openwrt，也不支持iptables之类操作防火墙转发，那你还需要一个真的网关，
本项目docker无法充当网关， 你的nas应该也是无法充当网关的，
按原项目作者的做法是使用linux系统当旁路网关，你有的话可以参考原项目，(start-web.sh)[https://github.com/Tilerphy/ps4broadcast/blob/master/start-web.sh]

没有的话nas可以考虑虚拟机安装openwrt当旁路网关，
不过这个坑就有点大了，随便找个教程容易把整个网络搞炸，

**Comment by BabyDriver2023** [comment]
> 大家的网关情况都不一样，我这里readme针对的是在使用这项目之前就已经有openwrt+uu配合ps5设置好了的情况，其他情况没法一概而论，
> 
> 如果你目前ps5连接的路由不是openwrt，也不支持iptables之类操作防火墙转发，那你还需要一个真的网关， 本项目docker无法充当网关， 你的nas应该也是无法充当网关的， 按原项目作者的做法是使用linux系统当旁路网关，你有的话可以参考原项目，(start-web.sh)[https://github.com/Tilerphy/ps4broadcast/blob/master/start-web.sh]
> 
> 没有的话nas可以考虑虚拟机安装openwrt当旁路网关， 不过这个坑就有点大了，随便找个教程容易把整个网络搞炸，

我现在是这样一个拓扑结构  ：
1.NAS里面跑的ps4broadcast 服务地址192.168.1.175
2.软路由里跑的openwrt(科学+UU）,openwrt LAN口地址192.168.1.253
3.PS5平时网关就是设置的192.168.1.253（OPWRT的）

还是说上面你指的ps4broadcast-docker要跑在openwrt的docker 服务里面？ 是这样么？
真心求教，感谢耐心解答！

**Comment by AoEiuV020** [comment]
这个组合都在一个子网那你的情况和我的很相似了，这就很合适，
首先ps5不用动，保持原本正常使用uu配置，
然后下载 https://github.com/AoEiuV020/ps4broadcast-docker/blob/main/firewall.user 到 192.168.1.253 openwrt中，
这个脚本中我的ip 192.168.2.45 改成你的 192.168.1.175 ，
然后脚本整个贴到 openwrt上的 /etc/firewall.user 文件末尾，
重启openwrt防火墙，/etc/init.d/firewall restart
就完成了， 
正常的话， 防火墙重启后状态页面中PREROUTING链会有1935和6667两个规则指向你的docker 192.168.1.175，几秒后uu会自动生成主机加速的规则把我们的挤下去，然后两秒内我们的规则又会重新置顶，就ok了，
<img width="1510" alt="image" src="https://github.com/AoEiuV020/ps4broadcast-docker/assets/11682198/037c2fb2-92f6-4f66-a944-60eee3094690">

这时候ps5上开启twitch直播，应该可以成功开启，但是twitch网站上自己的直播间看不到ps5，
这时候局域网中的obs添加vlc视频源，
rtmp://192.168.1.175/app/live_ddddddddd_xxxxxxxxxxxxxxxxxxxxxxx
live这串记得改成你自己的推流码，[获取推送码](https://dashboard.twitch.tv/u/aoeiuv020/settings/stream)，
等几秒延迟就能看到画面了，

**Comment by BabyDriver2023** [comment]
> 这个组合都在一个子网那你的情况和我的很相似了，这就很合适， 首先ps5不用动，保持原本正常使用uu配置， 然后下载 https://github.com/AoEiuV020/ps4broadcast-docker/blob/main/firewall.user 到 192.168.1.253 openwrt中， 这个脚本中我的ip 192.168.2.45 改成你的 192.168.1.175 ， 然后脚本整个贴到 openwrt上的 /etc/firewall.user 文件末尾， 重启openwrt防火墙，/etc/init.d/firewall restart 就完成了， 正常的话， 防火墙重启后状态页面中PREROUTING链会有1935和6667两个规则指向你的docker 192.168.1.175，几秒后uu会自动生成主机加速的规则把我们的挤下去，然后两秒内我们的规则又会重新置顶，就ok了， <img alt="image" width="1510" src="https://private-user-images.githubusercontent.com/11682198/331221418-037c2fb2-92f6-4f66-a944-60eee3094690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Njk2MzksIm5iZiI6MTcxNTg2OTMzOSwicGF0aCI6Ii8xMTY4MjE5OC8zMzEyMjE0MTgtMDM3YzJmYjItOTJmNi00ZjY2LWE5NDQtNjBlZWUzMDk0NjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE0MjIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MjZjMjcwNjBkZWIxZTFhZWJkY2FlNmE2YzQ0YWRlNWE1M2M0OGYyNGUzYWUyYjMwZmM0ZmIwN2MyNWVhNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JWgR8chQfd7Ca36x6HvD1x4WAvsFnjpS8Bf6b24nPBM">
> 
> 这时候ps5上开启twitch直播，应该可以成功开启，但是twitch网站上自己的直播间看不到ps5， 这时候局域网中的obs添加vlc视频源， rtmp://192.168.1.175/app/live_ddddddddd_xxxxxxxxxxxxxxxxxxxxxxx live这串记得改成你自己的推流码，[获取推送码](https://dashboard.twitch.tv/u/aoeiuv020/settings/stream)， 等几秒延迟就能看到画面了，

大致明白这个思路了，谢谢解答。

**Comment by BabyDriver2023** [comment]
![4bf5f2a42aa9770e6720069fe8108b5](https://github.com/AoEiuV020/ps4broadcast-docker/assets/124128728/ef2e9929-f4b1-4151-a515-cd932fe29cff)
![3b8410f1f9f4339f8de597144bbb6ad](https://github.com/AoEiuV020/ps4broadcast-docker/assets/124128728/9d566202-b943-4e15-94da-8340130756e4)
![d57c6bacac9d6fa22bcbb093bec46f6](https://github.com/AoEiuV020/ps4broadcast-docker/assets/124128728/7c1e3ab4-4279-486c-8dd4-a7f974ccad39)
哎糟心，按你说的把firewall.user脚本弄上去了，防火墙规则里也出现了1935和6667两个端口规则指向 192.168.10.175，但就是无法开播，确定192.168.10.175是可以访问的，1935和6667两个端口也是可以正常访问的状态。
后来干脆瞎折腾，把防火墙规则恢复之前状态，然后vi /etc/hosts（修改hosts)添加了如下：
![image](https://github.com/AoEiuV020/ps4broadcast-docker/assets/124128728/e161c27d-3954-420f-bd75-0406ea76cfb3)
等于DNS解析里直接把PS5访问这些域名（twitch 推流服务器域名）强制解析成访问192.168.10.175，重启OP好了 视频流正常到192.168.10.175了，B站上开播也有了画面，但弹幕始终无解。实在不知道问题在哪里，真心求教帮忙分析................

**Comment by AoEiuV020** [comment]
弹幕就不知道了，我没使用原项目的弹幕之类功能，这块估计过时了，B站好像改过相关消息协议，
